import type { Metadata } from 'next';

import '@/styles/layers.css';
import '@/styles/reset.css';
import { ThemeProvider } from 'next-themes';
import { darkTheme, lightTheme } from '@/styles/themes.css';
import { ThemeSwitch } from '@/components/common/ThemeSwitch';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function IndexLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          value={{ light: lightTheme, dark: darkTheme }}
        >
          <header>
            <nav>NAV</nav>
          </header>
          <ThemeSwitch />
          {children}
          <footer>FOOTER</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
