import type { Metadata } from 'next';

import '@/styles/layers.css';
import '@/styles/reset.css';
import { ThemeProvider } from 'next-themes';
import { darkTheme, lightTheme } from '@/styles/themes.css';
import localFont from 'next/font/local';
import { AppBarContainer } from '@/components/common/AppBarContainer';

const pretendard = localFont({
  src: '../../public/assets/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function IndexLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning className={pretendard.className}>
      <body>
        <ThemeProvider
          attribute="class"
          enableSystem
          value={{ light: lightTheme, dark: darkTheme }}
        >
          <AppBarContainer />
          {children}
          <footer>FOOTER</footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
